### __Machine Learning Models: Regression Test__

In [1]:
# import libraries
import numpy as np
import pandas as pd
import random
import io
import requests
from datetime import datetime, timezone, timedelta
import datetime as dt
import time
from collections import Counter
from PIL import Image
import PIL.Image

import six
from six import StringIO
import sys
from sklearn.tree import export_graphviz
#from sklearn.externals.six import StringIO  
from IPython.display import Image  
import pydotplus

# import matplotlib
from matplotlib import pyplot
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import matplotlib.image as mpimg

# import seaborn
import seaborn as sns

# import plotly graph objects
import plotly.graph_objs as go
import plotly.express as px

# import scipy.cluster.hierarchy
import scipy
import scipy.linalg as la
import scipy.cluster.hierarchy as sch
from scipy.cluster.vq import whiten, kmeans, vq
from scipy.stats import multivariate_normal
from scipy.stats import loguniform
from pathlib import Path

import warnings
warnings.filterwarnings('ignore')

# import category encoders
#import category_encoders as ce

import statsmodels.api as sm

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
import sklearn.model_selection as model_selection
import sklearn.model_selection as cross_validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
import sklearn.metrics as metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import log_loss
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import plot_roc_curve
from sklearn.metrics import average_precision_score, f1_score, classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_precision_recall_curve, plot_confusion_matrix
from sklearn.feature_selection import RFE
from sklearn import linear_model, datasets
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.svm import SVR
from sklearn import tree
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
#from sklearn.externals.six import StringIO  
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
import sklearn.gaussian_process as gp
from sklearn.neural_network import MLPClassifier

import xgboost as xgb
from xgboost import XGBClassifier, XGBRegressor

#for showing 2D plot
%matplotlib inline 

# to be able to see multiple ouputs from sungle cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# Training Dataset import
train_dfr = pd.read_csv('work_df3_scaledfeatur_eng.csv')
train_dfr.info()
train_dfr.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520681 entries, 0 to 520680
Data columns (total 52 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   year                   520681 non-null  int64
 1   month                  520681 non-null  int64
 2   day_of_week            520681 non-null  int64
 3   mkt_carrier_fl_num     520681 non-null  float64
 4   tail_num               520681 non-null  int64
 5   origin                 520681 non-null  int64
 6   origin_city            520681 non-null  int64
 7   dest                   520681 non-null  int64
 8   dest_city              520681 non-null  int64
 9   crs_elapsed_time       520681 non-null  float64
 10  flights                520681 non-null  float64
 11  distance               520681 non-null  float64
 12  mkt_unique_carrier_AA  520681 non-null  int64
 13  mkt_unique_carrier_AS  520681 non-null  int64
 14  mkt_unique_carrier_B6  520681 non-null  int64
 15  mkt_unique_carrier_DL  520681 non-null  int64
 16  mkt_unique_carrier_F9  520681 non-null  int64
 17  mkt_unique_carrier_G4  520681 non-null  int64
 18  mkt_unique_carrier_HA  520681 non-null  int64
 19  mkt_unique_carrier_NK  520681 non-null  int64
 20  mkt_unique_carrier_UA  520681 non-null  int64
 21  mkt_unique_carrier_VX  520681 non-null  int64
 22  mkt_unique_carrier_WN  520681 non-null  int64
 23  op_unique_carrier_9E   520681 non-null  int64
 24  op_unique_carrier_9K   520681 non-null  int64
 25  op_unique_carrier_AA   520681 non-null  int64
 26  op_unique_carrier_AS   520681 non-null  int64
 27  op_unique_carrier_AX   520681 non-null  int64
 28  op_unique_carrier_B6   520681 non-null  int64
 29  op_unique_carrier_C5   520681 non-null  int64
 30  op_unique_carrier_CP   520681 non-null  int64
 31  op_unique_carrier_DL   520681 non-null  int64
 32  op_unique_carrier_EM   520681 non-null  int64
 33  op_unique_carrier_EV   520681 non-null  int64
 34  op_unique_carrier_F9   520681 non-null  int64
 35  op_unique_carrier_G4   520681 non-null  int64
 36  op_unique_carrier_G7   520681 non-null  int64
 37  op_unique_carrier_HA   520681 non-null  int64
 38  op_unique_carrier_KS   520681 non-null  int64
 39  op_unique_carrier_MQ   520681 non-null  int64
 40  op_unique_carrier_NK   520681 non-null  int64
 41  op_unique_carrier_OH   520681 non-null  int64
 42  op_unique_carrier_OO   520681 non-null  int64
 43  op_unique_carrier_PT   520681 non-null  int64
 44  op_unique_carrier_QX   520681 non-null  int64
 45  op_unique_carrier_UA   520681 non-null  int64
 46  op_unique_carrier_VX   520681 non-null  int64
 47  op_unique_carrier_WN   520681 non-null  int64
 48  op_unique_carrier_YV   520681 non-null  int64
 49  op_unique_carrier_YX   520681 non-null  int64
 50  op_unique_carrier_ZW   520681 non-null  int64
 51  target_class           520681 non-null  int64
dtypes: float64(4), int64(48)
memory usage: 206.6 MB

,year,month,day_of_week,mkt_carrier_fl_num,tail_num,origin,origin_city,dest,dest_city,crs_elapsed_time,...,op_unique_carrier_OO,op_unique_carrier_PT,op_unique_carrier_QX,op_unique_carrier_UA,op_unique_carrier_VX,op_unique_carrier_WN,op_unique_carrier_YV,op_unique_carrier_YX,op_unique_carrier_ZW,target_class
0,2019,5,2,1.007068,3,2,2,4,5,0.425950,...,0,0,0,0,0,0,0,1,0,1
1,2019,5,2,1.036667,3,1,1,5,5,0.077483,...,0,0,0,0,0,0,0,1,0,1
2,2019,5,2,-1.447481,2,5,5,5,5,-0.061903,...,0,0,0,0,0,0,0,0,0,1
3,2019,5,2,-1.288723,1,5,4,3,3,2.196161,...,0,0,0,0,0,0,0,0,0,1
4,2019,5,2,-1.186473,3,2,2,5,5,-0.744898,...,0,0,0,0,0,0,0,0,0,1

In [9]:
# start time to measure the time of the program execution
start_time = time.time()

# Training Dataset import
time_date_fl = pd.read_csv('crs_fl_data.csv')

# get date, month, year and hours as columns
time_date_fl['day_fl'] = [str(int(x[8:])) for x in time_date_fl['fl_date']]
time_date_fl['hours_fl'] = [str(int(x/100)) for x in time_date_fl['crs_arr_time']]
time_date_fl['year_fl'] = train_dfr['year'].astype(str)
time_date_fl['month_fl'] = train_dfr['month'].astype(str)

# check values in variables
time_date_fl['day_fl'].unique()
time_date_fl['hours_fl'].unique()
time_date_fl['year_fl'].unique()
time_date_fl['month_fl'].unique()

# check dataframe
time_date_fl.info()
time_date_fl.head()

# get dummy variables for the four variables above
dummy_features = ['year_fl', 'month_fl', 'day_fl', 'hours_fl']
df_dummy = pd.get_dummies(time_date_fl[dummy_features])
df_dummy

# combine dummy variables with work_df
train_df = pd.concat([train_dfr, df_dummy], axis=1)

# remove variables related to dummy_features from train_df
# also remove 'flights' variable
remove_lower_features = ['flights', 'year', 'month', 'day_of_week', 'target_class']
train_df = train_df.drop(remove_lower_features, axis=1)

# check
train_df.info()
train_df.head()

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31'], dtype=object)

array(['10', '1', '20', '9', '0', '23', '21', '6', '18', '7', '17', '12',
       '15', '22', '19', '16', '13', '8', '2', '14', '11', '5', '3', '4'],
      dtype=object)

array(['2019', '2018'], dtype=object)

array(['5', '4', '3', '7', '10', '6', '8', '2', '11', '12', '9', '1'],
      dtype=object)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520681 entries, 0 to 520680
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   fl_date       520681 non-null  object
 1   crs_dep_time  520681 non-null  int64
 2   crs_arr_time  520681 non-null  int64
 3   day_fl        520681 non-null  object
 4   hours_fl      520681 non-null  object
 5   year_fl       520681 non-null  object
 6   month_fl      520681 non-null  object
dtypes: int64(2), object(5)
memory usage: 27.8+ MB

      fl_date  crs_dep_time  crs_arr_time day_fl hours_fl year_fl month_fl
0  2019-05-01           655          1044      1       10    2019        5
1  2019-05-01          1441           175      1        1    2019        5
2  2019-05-01          1730          2044      1       20    2019        5
3  2019-05-01           829          1025      1       10    2019        5
4  2019-05-01          1854          2019      1       20    2019        5

,year_fl_2018,year_fl_2019,month_fl_1,month_fl_10,month_fl_11,month_fl_12,month_fl_2,month_fl_3,month_fl_4,month_fl_5,...,hours_fl_21,hours_fl_22,hours_fl_23,hours_fl_3,hours_fl_4,hours_fl_5,hours_fl_6,hours_fl_7,hours_fl_8,hours_fl_9
0,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520676,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
520677,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
520678,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
520679,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
520680,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520681 entries, 0 to 520680
Columns: 116 entries, mkt_carrier_fl_num to hours_fl_9
dtypes: float64(3), int64(44), uint8(69)
memory usage: 221.0 MB

,mkt_carrier_fl_num,tail_num,origin,origin_city,dest,dest_city,crs_elapsed_time,distance,mkt_unique_carrier_AA,mkt_unique_carrier_AS,...,hours_fl_21,hours_fl_22,hours_fl_23,hours_fl_3,hours_fl_4,hours_fl_5,hours_fl_6,hours_fl_7,hours_fl_8,hours_fl_9
0,1.007068,3,2,2,4,5,0.425950,0.655085,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1.036667,3,1,1,5,5,0.077483,-0.063268,1,0,...,0,0,0,0,0,0,0,0,0,0
2,-1.447481,2,5,5,5,5,-0.061903,-0.071780,0,0,...,0,0,0,0,0,0,0,0,0,0
3,-1.288723,1,5,4,3,3,2.196161,2.193928,0,0,...,0,0,0,0,0,0,0,0,0,0
4,-1.186473,3,2,2,5,5,-0.744898,-0.795240,0,0,...,0,0,0,0,0,0,0,0,0,0

--- 4.667991876602173 seconds ---

In [12]:
# remove features with the lowest raning in the feature selection process
#remove_lower_features = ['flights', 'mkt_unique_carrier_HA', 'op_unique_carrier_9K',
#                         'op_unique_carrier_G4','op_unique_carrier_PT','op_unique_carrier_YV']

In [13]:
# start time to measure the time of the program execution
start_time = time.time()

# import dataset that contains two target variables
reduced_train_df = pd.read_csv('reduced_train_df.csv')

# set up the target variable for regression
train_df['target'] = reduced_train_df['arr_delay']

# check
train_df.info()
train_df.head(3)

# check columns in train_df
train_df.columns.tolist()

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520681 entries, 0 to 520680
Columns: 117 entries, mkt_carrier_fl_num to target
dtypes: float64(4), int64(44), uint8(69)
memory usage: 224.9 MB

,mkt_carrier_fl_num,tail_num,origin,origin_city,dest,dest_city,crs_elapsed_time,distance,mkt_unique_carrier_AA,mkt_unique_carrier_AS,...,hours_fl_22,hours_fl_23,hours_fl_3,hours_fl_4,hours_fl_5,hours_fl_6,hours_fl_7,hours_fl_8,hours_fl_9,target
0,1.007068,3,2,2,4,5,0.425950,0.655085,1,0,...,0,0,0,0,0,0,0,0,0,99.0
1,1.036667,3,1,1,5,5,0.077483,-0.063268,1,0,...,0,0,0,0,0,0,0,0,0,4.0
2,-1.447481,2,5,5,5,5,-0.061903,-0.071780,0,0,...,0,0,0,0,0,0,0,0,0,15.0

['mkt_carrier_fl_num',
 'tail_num',
 'origin',
 'origin_city',
 'dest',
 'dest_city',
 'crs_elapsed_time',
 'distance',
 'mkt_unique_carrier_AA',
 'mkt_unique_carrier_AS',
 'mkt_unique_carrier_B6',
 'mkt_unique_carrier_DL',
 'mkt_unique_carrier_F9',
 'mkt_unique_carrier_G4',
 'mkt_unique_carrier_HA',
 'mkt_unique_carrier_NK',
 'mkt_unique_carrier_UA',
 'mkt_unique_carrier_VX',
 'mkt_unique_carrier_WN',
 'op_unique_carrier_9E',
 'op_unique_carrier_9K',
 'op_unique_carrier_AA',
 'op_unique_carrier_AS',
 'op_unique_carrier_AX',
 'op_unique_carrier_B6',
 'op_unique_carrier_C5',
 'op_unique_carrier_CP',
 'op_unique_carrier_DL',
 'op_unique_carrier_EM',
 'op_unique_carrier_EV',
 'op_unique_carrier_F9',
 'op_unique_carrier_G4',
 'op_unique_carrier_G7',
 'op_unique_carrier_HA',
 'op_unique_carrier_KS',
 'op_unique_carrier_MQ',
 'op_unique_carrier_NK',
 'op_unique_carrier_OH',
 'op_unique_carrier_OO',
 'op_unique_carrier_PT',
 'op_unique_carrier_QX',
 'op_unique_carrier_UA',
 'op_unique_carrier_VX',
 'op_unique_carrier_WN',
 'op_unique_carrier_YV',
 'op_unique_carrier_YX',
 'op_unique_carrier_ZW',
 'year_fl_2018',
 'year_fl_2019',
 'month_fl_1',
 'month_fl_10',
 'month_fl_11',
 'month_fl_12',
 'month_fl_2',
 'month_fl_3',
 'month_fl_4',
 'month_fl_5',
 'month_fl_6',
 'month_fl_7',
 'month_fl_8',
 'month_fl_9',
 'day_fl_1',
 'day_fl_10',
 'day_fl_11',
 'day_fl_12',
 'day_fl_13',
 'day_fl_14',
 'day_fl_15',
 'day_fl_16',
 'day_fl_17',
 'day_fl_18',
 'day_fl_19',
 'day_fl_2',
 'day_fl_20',
 'day_fl_21',
 'day_fl_22',
 'day_fl_23',
 'day_fl_24',
 'day_fl_25',
 'day_fl_26',
 'day_fl_27',
 'day_fl_28',
 'day_fl_29',
 'day_fl_3',
 'day_fl_30',
 'day_fl_31',
 'day_fl_4',
 'day_fl_5',
 'day_fl_6',
 'day_fl_7',
 'day_fl_8',
 'day_fl_9',
 'hours_fl_0',
 'hours_fl_1',
 'hours_fl_10',
 'hours_fl_11',
 'hours_fl_12',
 'hours_fl_13',
 'hours_fl_14',
 'hours_fl_15',
 'hours_fl_16',
 'hours_fl_17',
 'hours_fl_18',
 'hours_fl_19',
 'hours_fl_2',
 'hours_fl_20',
 'hours_fl_21',
 'hours_fl_22',
 'hours_fl_23',
 'hours_fl_3',
 'hours_fl_4',
 'hours_fl_5',
 'hours_fl_6',
 'hours_fl_7',
 'hours_fl_8',
 'hours_fl_9',
 'target']

--- 3.4811689853668213 seconds ---

In [16]:
train_df.iloc[:, 116]

0         99.0
1          4.0
2         15.0
3         12.0
4         35.0
          ...
520676   -10.0
520677   -10.0
520678   -19.0
520679   -15.0
520680    -4.0
Name: target, Length: 520681, dtype: float64

In [29]:
train_df.to_csv('reg_train_df.csv', index=False)

#### __Regression Models - Initialize__
> - Linear Regression
> - Ridge Regression
> - Lasso Regression
> - Decision Tree Regressor: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html
> - Random Forest Regressor: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html
> - KNN: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
> - XGBoost: https://machinelearningmastery.com/xgboost-for-regression/

> - Hyperparameter Tuning: Randomizer https://machinelearningmastery.com/hyperparameter-optimization-with-random-search-and-grid-search/

In [17]:
# Assign X & y
X = train_df.iloc[:, :116].values
y = train_df.iloc[:, 116].values

# split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [18]:
# start time to measure the time of the program execution
start_time = time.time()

# Fit Random Forest Model
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

LinearRegression()

--- 8.959113597869873 seconds ---

In [19]:
# start time to measure the time of the program execution
start_time = time.time()

# Fit Random Forest Model
rr = Ridge()
rr.fit(X_train, y_train)
y_pred_rr = rr.predict(X_test)

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

Ridge()

--- 0.9299898147583008 seconds ---

In [20]:
# start time to measure the time of the program execution
start_time = time.time()

# Fit Random Forest Model
ls = Lasso()
ls.fit(X_train, y_train)
y_pred_ls = ls.predict(X_test)

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

Lasso()

--- 1.4658112525939941 seconds ---

In [21]:
# start time to measure the time of the program execution
start_time = time.time()

# Fit Random Forest Model
dr = DecisionTreeRegressor(random_state=0)
dr.fit(X_train, y_train)
y_pred_dr = dr.predict(X_test)

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

DecisionTreeRegressor(random_state=0)

--- 34.53614902496338 seconds ---

In [22]:
# start time to measure the time of the program execution
start_time = time.time()

# Fit Random Forest Model
rfr = RandomForestRegressor(random_state=0)
rfr.fit(X_train, y_train)
y_pred_rfr = rfr.predict(X_test)

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

RandomForestRegressor(random_state=0)

--- 2741.167586326599 seconds ---

In [23]:
# start time to measure the time of the program execution
start_time = time.time()

# Fit Random Forest Model
knn = KNeighborsRegressor()
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

KNeighborsRegressor()

--- 25863.26190161705 seconds ---

In [24]:
# start time to measure the time of the program execution
start_time = time.time()

# Fit Random Forest Model
xgb = XGBRegressor()
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=8,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

--- 74.70172381401062 seconds ---

In [36]:
# start time to measure the time of the program execution
start_time = time.time()

# function for measuring the performance of regression models
def regression_metrics(y_test, X_test, y_pred_lst, n, k):
    
    linear_r = []
    ridge = []
    lasso = []
    decision_r = []
    rf_r = []
    knn_r = []
    xgb_r = []
    
    model_lst = [linear_r, ridge, lasso, decision_r, rf_r, knn_r, 
                 xgb_r]
    
    n= 0
    
    # for each y_pred in the list, compute the metrics
    for item in y_pred_lst:
        r2_test = r2_score(y_test, item)
        adjusted_R2 = 1 - ((n - 1) / (n - k - 1)) * (1 - r2_test)
        mae_test = mean_absolute_error(y_test, item)
        mse_test = mean_squared_error(y_test, item)
        rmse_test = np.sqrt(mean_squared_error(y_test, item))
        
        model_lst[n] = [r2_test, adjusted_R2, mae_test, mse_test, rmse_test]
        n += 1
        
    df_metrics_summary = pd.DataFrame({'linear_reg': model_lst[0], 'ridge': model_lst[1], 'lasso': model_lst[2],
                                    'decision_reg': model_lst[3], 'random_forest': model_lst[4], 
                                    'knn': model_lst[5], 'xgboost': model_lst[6]},
                                      index = ['R2', 'Adjusted_R2','MAE', 'MSE', 'RMSE'])

    return df_metrics_summary

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

--- 0.0 seconds ---

In [37]:
# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

n = len(X_test)
k = len(train_df.columns.tolist())-1

y_pred_lst = [y_pred_lr, y_pred_rr, y_pred_ls, y_pred_dr, y_pred_rfr,
              y_pred_knn, y_pred_xgb]

regression_metrics(y_test, X_test, y_pred_lst, n, k)

# print the overall program runtime.
print(f"\n\n--- {(time.time() - start_time)} seconds ---")

--- 8.410559892654419 seconds ---

,linear_reg,ridge,lasso,decision_reg,random_forest,knn,xgboost
R2,0.023922,0.023923,0.000901,-0.991440,-0.013324,-0.119903,0.031551
Adjusted_R2,0.991657,1.000000,1.008688,1.034938,1.026902,1.039997,1.043624
MAE,29.083519,29.083943,29.710413,39.524953,29.537413,31.872378,28.730370
MSE,3263.892083,3263.886449,3340.870890,6659.143455,3388.436352,3744.824543,3238.380278
RMSE,57.130483,57.130434,57.800267,81.603575,58.210277,61.194972,56.906768

--- 8.483684778213501 seconds ---